{{- range $key, $instance := .Values.instances -}}
{{- range $i, $secret := $instance.secrets -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "{{ $instance.name }}-{{ $secret.name }}"
spec:
  backendType: systemManager
  data:
    {{ if $secret.property }}
    - key: "{{ $secret.ref }}"
      name: "{{ $secret.property }}"
    {{ else }}
      {{ range $j, $property := $secret.properties }}
      - key: "{{ $secret.ref }}"
        name: "{{ $property.name }}"
        property: "{{ $property.key }}"
      {{ end }}
    {{ end }}
---
{{- end }}
{{- end }}
{{ if .Values.localSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: local-citsbot.config
type: Opaque
data:
  token: {{ .Values.localSecrets.token | b64enc }}
  imgurClientId: {{ .Values.localSecrets.imgurClientId | b64enc }}
{{ end }}
