name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  build_and_push:
    name: Build and Push to GitHub Registry
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

      - name: Parse tagged version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:11}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/uwacsds/citsbot:${{ steps.vars.outputs.tag }}
